.TH "GETRFC" "1" "21 Jul 2020" "Version 0.0.1" "User Commands"
.SH NAME
getrfc \- RFC from terminal
.SH SYNOPSIS
.B getrfc [OPTIONS] [KEYWORD [KEYWORD ...]]
.SH DESCRIPTION
.B getrfc
is a command-line tool to get a RFC. \fBgetrfc\fR shows the rfc content from your number.
.PP
.B Features
.PP
  * Fast and clean;
  * Show the list of RFCs;
  * Show the RFC from your number;

.SH OPTIONS
.TP
.BI "-h, --help"
Show help text and exit.
.TP
.BI "-l, --list" N
Show the list of RFCs.
.TP
.BI "RFC number" N
Show the RFC.
